# <right><div style="font-family: Times New Roman; font-size: 30px; border-radius : 10px; background-color: #a4e5efff; color: #000000ff; padding: 12px; line-height: 0.7;">1. LIST </div></center>


In [ ]:
# Membuat List
my_list = [10, "Python", 3.14, True]
print(my_list)


[10, 'Python', 3.14, True]


In [ ]:
# Menambahkan Elemen
my_list.append("AI") #fungsi append
print(my_list)

[10, 'Python', 3.14, True, 'AI']


In [ ]:
# Menghapus Elemen

my_list = [10, 'Python', 3.14, True, 'AI']
my_list.remove(10)
print(my_list)

['Python', 3.14, True, 'AI']


In [ ]:
# Update Elemen

my_list = ['Python', 3.14, True, 'AI']
my_list[1] = "Machine Learning"

print(my_list)

['Python', 'Machine Learning', True, 'AI']


In [ ]:
# Menampilkan List Langsung

print("Isi list:", my_list)


Isi list: [10, 'Machine Learning', 3.14, True]


# <right><div style="font-family: Times New Roman; font-size: 30px; border-radius : 10px; background-color: #a4e5efff; color: #000000ff; padding: 12px; line-height: 0.7;">2. ARRAY </div></center>


In [4]:
# Membuat array bertipe integer

import array as arr
my_array = arr.array('i', [1, 2, 3, 4, 5])
print(my_array)

array('i', [1, 2, 3, 4, 5])


In [6]:
# Operasi dasar

import array as arr
my_array = arr.array('i', [1, 2, 3, 4, 5])
my_array.append(6)     # Tambah elemen
my_array.remove(2)     # Hapus elemen
my_array[0] = 10       # Update elemen
print(my_array)

array('i', [10, 3, 4, 5, 6])


In [9]:
# Menampilkan array (butuh loop jika ingin tiap elemen)

import array as arr
my_array = arr.array('i', [10, 3, 4, 5, 6])

print("Isi array:", end=" ")
for x in my_array:
    print(x, end=" ")


Isi array: 10 3 4 5 6 

# <right><div style="font-family: Times New Roman; font-size: 30px; border-radius : 10px; background-color: #a4e5efff; color: #000000ff; padding: 12px; line-height: 0.7;">3. PERBEDAAN LIST DAN ARRAY </div></center>


In [1]:
# --- List ---

my_list = [90, "Nasi Goreng", 3.1, True]   # campuran tipe data

my_list.append("Bisnis Digital")

print("List:", my_list)

List: [90, 'Nasi Goreng', 3.1, True, 'Bisnis Digital']


In [53]:
# --- Array dengan modul array ---

import array as arr

my_array = arr.array('i', [100, 200, 300, 400, 500])  # semua integer

my_array.append(600)

print("Array (module array):", my_array.tolist())

Array (module array): [100, 200, 300, 400, 500, 600]


In [56]:
# --- Array dengan NumPy ---

import numpy as np

np_array = np.array([10, 20, 30, 40, 50])

print("NumPy Array:", np_array)

print("Operasi aritmatika (+10):", np_array + 100)

NumPy Array: [10 20 30 40 50]
Operasi aritmatika (+10): [110 120 130 140 150]


In [11]:
# Pembuatan Array Numpy

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)  

[1 2 3 4]


# <right><div style="font-family: Times New Roman; font-size: 30px; border-radius : 10px; background-color: #a4e5efff; color: #000000ff; padding: 12px; line-height: 0.7;">4. MEMBUAT MATRIKS DENGAN NUMPY </div></center>


In [ ]:
# Membuat Matriks 3x3

matrik_np = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(matrik_np)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
import numpy as np
matrix = np.random.randint(0,10, size = (9, 9))
print(matrix)

[[7 6 5 3 5 1 9 9 2]
 [1 6 1 3 0 9 5 3 3]
 [4 4 6 9 6 8 7 6 7]
 [1 7 3 4 8 3 2 4 2]
 [7 6 3 6 1 8 6 5 7]
 [6 0 8 8 7 5 8 5 1]
 [5 9 7 5 1 3 3 7 1]
 [9 1 3 9 2 2 2 5 4]
 [5 7 9 1 9 4 8 8 3]]


In [18]:
# Membuat array berisi nol.

zeros = np.zeros((3, 4))  # Array 3x4
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# Membuat array berisi satu.

ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Membuat array dengan rentang nilai (seperti range() di Python, tapi lebih fleksibel).

arr = np.arange(0, 10, 2)
print(arr)  # [0 2 4 6 8]

[0 2 4 6 8]


In [21]:
# Membuat array dengan jumlah elemen tertentu yang dibagi rata dalam suatu interval.

linspace = np.linspace(0, 1, 5)
print(linspace)  # [0.   0.25 0.5  0.75 1.  ]



[0.   0.25 0.5  0.75 1.  ]


In [22]:
# Membuat array dengan nilai acak dari distribusi seragam (0 hingga 1).

random_arr = np.random.rand(2, 3)
print(random_arr)

[[0.46417435 0.89409039 0.13085447]
 [0.20214969 0.65114919 0.57899865]]


In [23]:
# Bentuk array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 

(2, 3)


In [24]:
# Jumlah dimensi (rank) dari array

arr = np.array([[[1, 2], [3, 4]]])
print(arr.ndim)  

3


In [25]:
# Tipe data elemen dalam array (int, float, bool, dll).

arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  

float32


In [26]:
# Jumlah total elemen dalam array.

arr = np.zeros((3, 4))
print(arr.size)

12


In [27]:
# Indexing & Slicing

# Contoh 1D:

arr = np.array([10, 20, 30, 40])

print(arr[0])    
print(arr[-1])   

# Contoh 2D:

arr = np.array([[1, 2], [3, 4]])
print(arr[0, 1]) 

10
40
2


In [28]:
# Slicing (Mengambil Bagian Array)

# Contoh 1D:

arr = np.arange(10)
print(arr[2:7:2])  

# Contoh 2D:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0:2, 1:3]) 

[2 4 6]
[[2 3]
 [5 6]]


# <right><div style="font-family: Times New Roman; font-size: 30px; border-radius : 10px; background-color: #a4e5efff; color: #000000ff; padding: 12px; line-height: 0.7;">5. STATISTICAL FUNCTIONS </div></center>


In [ ]:
# Koding T13.1 numpy.amin() and numpy.amax()  

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
min_value = np.amin(arr)
print("Nilai Minimum:", min_value)

max_value = np.amax(arr)
print("Nilai Maksimum:", max_value)

Nilai Minimum: 1
Nilai Maksimum: 9
Nilai Maksimum: 9


In [30]:
# Koding T13.2 numpy.ptp()

# Menghitung rentang (range) dari array
range_value = np.ptp(arr)
print("\nArray:", arr)
print("Rentang:", range_value)


Array: [3 1 4 1 5 9 2 6 5]
Rentang: 8


In [32]:
# Koding T13.3 numpy.percentile()    

# Membuat array NumPy
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

# Menghitung persentil ke-25 (Q1)
q1 = np.percentile(arr, 25)

# Menghitung persentil ke-50 (median)
median = np.percentile(arr, 50)

# Menghitung persentil ke-75 (Q3)
q3 = np.percentile(arr, 75)

# Menampilkan hasil
print("Q1 (Persentil ke-25):", q1)
print("Median (Persentil ke-50):", median)
print("Q3 (Persentil ke-75):", q3)

Q1 (Persentil ke-25): 2.0
Median (Persentil ke-50): 4.0
Q3 (Persentil ke-75): 5.0


In [ ]:
# Koding T13.4 numpy.median()  


# Membuat array NumPy
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

# Menggunakan numpy.median() untuk menghitung median
median_value = np.median(arr)
print("Array:", arr)
print("Median:", median_value)

Array: [3 1 4 1 5 9 2 6 5]
Median: 4.0


In [40]:
#Koding T13.5  numpy.mean()

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Array:", arr)
print("Rata-rata (mean):", np.mean(arr))

Array: [3 1 4 1 5 9 2 6 5]
Rata-rata (mean): 4.0


In [41]:
#Koding T13.6 numpy.average()

average = np.average(arr)
print(average)

4.0


In [43]:
#Koding T13.7 Standard Deviation

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
# Menghitung standar deviasi dari array arr
std_deviation = np.std(arr)
print("Standar Deviasi:", std_deviation)

Standar Deviasi: 2.449489742783178


In [44]:
# Koding T13.8 variance     

# Membuat array NumPy
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

# Menghitung varians dari array arr
variance = np.var(arr)
print("Array:", arr)
print("Varians:", variance)

Array: [3 1 4 1 5 9 2 6 5]
Varians: 6.0
